// Official Rules content for /terms.
// Extracted verbatim from the source Word document and mirrored 1:1 by the
// Terms & Conditions frame in Figma (Creator-Startup, node 5209-13).
// Numbering follows the document's own list definitions:
//   level 0 -> "1."   level 1 -> "1.1"   level 2 -> "(A)"
// DO NOT reword anything here — this is legal copy.

export type Run = { t: string; b?: true; i?: true; u?: true };

export type Block =
  | { type: "title"; runs: Run[] }
  | { type: "banner"; runs: Run[] }
  | { type: "h0" | "n1" | "n2"; num: string; runs: Run[]; just?: true }
  | { type: "body"; runs: Run[] }
  | { type: "table"; rows: string[][] };

export const TERMS_BLOCKS: Block[] = [
  { type: "title", runs: [{ t: "Official Rules", b: true }] },
  { type: "banner", runs: [{ t: "PRELIMINARY DISCLOSURES", b: true }] },
  { type: "h0", num: "1.", runs: [{ t: "NO PURCHASE OR PAYMENT OF ANY KIND IS NECESSARY TO ENTER OR WIN THIS CONTEST. YOU MUST BE 18 YEARS OF AGE (OR THE AGE OF MAJORITY IN YOUR JURISDICTION) OR OLDER AND A LEGAL RESIDENTOF THE UNITED STATES TO PARTICIPATE. VOID WHERE PROHIBITED.", b: true }], just: true },
  { type: "banner", runs: [{ t: "PROMOTION PARTIES", b: true }] },
  { type: "h0", num: "2.", runs: [{ t: "PROMOTION ORIGINATOR; ELIGIBLE PARTICIPANTS; INELIGIBLE PARTICIPANTS", b: true }], just: true },
  { type: "n1", num: "2.1", runs: [{ t: "Promotion Originator. ", b: true }, { t: "The BIG IDEA CONTEST" }, { t: " (“Contest” or “Promotion”)", b: true }, { t: " is sponsored by" }, { t: " ", b: true }, { t: "Adobe Inc" }, { t: ". (“Sponsor”) ", b: true }, { t: " and is originated by Colin and Samir LLC" }, { t: ", ", b: true }, { t: "its affiliates and subsidiaries" }, { t: " (collectively, “Colin and Samir”) ", b: true }, { t: "located at 2049 Century Park East, Suite 1400, Los Angeles, CA 90067." }], just: true },
  { type: "n1", num: "2.2", runs: [{ t: "Eligible Participants. ", b: true }, { t: "The Promotion is open only to persons meeting all the requirements recited in Section 1 (“" }, { t: "Participant(s),", b: true }, { t: "” “" }, { t: "You,", b: true }, { t: "” “" }, { t: "Your", b: true }, { t: "”). By participating in the Promotion Participants agree to be bound by these official rules (“" }, { t: "Official Rules", b: true }, { t: "”)." }], just: true },
  { type: "n2", num: "(A)", runs: [{ t: "It is the responsibility of any Participant to ensure that their participation in the Promotion is in compliance with applicable regulations and policies, including any government gift and ethics rules applicable to you. If you have questions about whether you can accept the prize for your participation in this Promotion, please contact your organization’s ethics office, legal counsel or designated official.  By participating in the Promotion, you are confirming that you are eligible to receive the prize." }], just: true },
  { type: "n1", num: "2.3", runs: [{ t: "Ineligible Participants. ", b: true }, { t: "No one who is an independent contractor, officer, or director of Colin and Samir, Sponsor or any of their agents, representatives, advertising, promotion, publicity and fulfillment agencies, legal advisors, successors and assigns, and any other company or person that is involved with the production, design, execution, administration, sponsorship  or distribution of this Promotion (collectively, the “" }, { t: "Released Parties", b: true }, { t: "”), is eligible to enter or win, nor is anyone who lives with (whether or not related), or who is an immediate family member of, any one of the Released Parties (i.e., parents, siblings, children and their respective spouses, regardless of where they reside). The Promotion is subject to all applicable federal, state, territorial, provincial, municipal and local laws and regulations and is void where prohibited or restricted by law." }], just: true },
  { type: "banner", runs: [{ t: "PROMOTION SCHEDULE", b: true }] },
  { type: "h0", num: "3.", runs: [{ t: "PROMOTION PHASES; SCHEDULE; TIMING", b: true }] },
  { type: "n1", num: "3.1", runs: [{ t: "Promotion Phases. ", b: true }, { t: "The Promotion comprises the start and end times, separate entry phase (the “" }, { t: "Entry Phase", b: true }, { t: "”), judging phase (“" }, { t: "Judging Phase", b: true }, { t: "”), and winner selection phase (“" }, { t: "Winner Selection Phase", b: true }, { t: "”), all phases collectively comprising the “Promotion Period”, as detailed in the schedule below:" }], just: true },
  { type: "n1", num: "3.2", runs: [{ t: "Schedule.", b: true }] },
  { type: "table", rows: [
      ["", "Entry Phase", "Judging Phase", "Winner Selection Phase"],
      ["Open  09:00 AM PT", "8/17/26", "9/18/26", "On or about:"],
      ["Close  11:59 PM PT", "9/17/26", "9/21/26", "9/22/26"],
    ] },
  { type: "n1", num: "3.3", runs: [{ t: "Timing. ", b: true }, { t: "EACH PARTICIPANT IS RESPONSIBLE FOR MAKING THE NECESSARY ADJUSTMENTS FOR TIMING OF THE VARIOUS PHASES IN SECTION 3.2 ABOVE BASED ON PARTICIPANT’S LOCATION AND TIME ZONE. Colin and Samir’s computer is the official time-keeping device for the Contest." }], just: true },
  { type: "banner", runs: [{ t: "PROMOTION TERMS", b: true }] },
  { type: "h0", num: "4.", runs: [{ t: "HOW TO ENTER; LIMITS ON ENTRIES; TEAM SUBMISSIONS", b: true }] },
  { type: "n1", num: "4.1", runs: [{ t: "How to Enter (“Entry Requirements”). ", b: true }, { t: "To submit an Entry anytime during the Promotion Entry Phase:" }], just: true },
  { type: "n2", num: "(A)", runs: [{ t: "Create a video pitching your idea for a dream creative project. A Submission (defined below)  must be in video format and must use one or more Adobe products or services. In the submission, tell us your idea, why you’re excited about it, what’s holding you back from making it and how you would use the Grand Prize to develop, produce or complete the project. Upload your video to YouTube and submit the link (unlisted or public) via https://bigideafund.colinandsamir.com/ (“" }, { t: "the Site", b: true }, { t: "”) (following the Submission Guidelines in Section 5.1, collectively, the “" }, { t: "Submission", b: true }, { t: "”)." }], just: true },
  { type: "n2", num: "(B)", runs: [{ t: "Your Submission, along with your name, age or year of birth, mail or email address, or user ID, and other required non-personal information, acknowledges Your acceptance of these Official Rules as directed (all elements together comprising the eligible “" }, { t: "Entry", b: true }, { t: "” or “" }, { t: "Entries", b: true }, { t: "”)." }], just: true },
  { type: "n1", num: "4.2", runs: [{ t: "Limits on Entries. ", b: true }, { t: "Each Participant may submit (on behalf of him/herself and any associated Contributors) only 1 Entry during the Promotion Entry Phase, and regardless of the number of Entries entered, each Participant is only eligible to win 1 prize in the Promotion. Each Entry must correspond to a single Participant using a single email address. Participants may not use multiple email addresses or alternate user identities in an attempt to submit more Entries than are allowed from a single Participant. Completed Entries must be entered and received electronically during the Entry Phase to be eligible for prizes. If the Promotion consists of multiple separate entry phases, then Entries received during a given Entry Phase will only be considered for the particular Entry Phase and corresponding prize at issue, and will not be included, rolled over, or considered for subsequent Entry Phases or prizes. Entries received by other methods will not be accepted, and no entries will be acknowledged or returned. Colin and Samir cannot guarantee that all persons attempting to enter will be able to participate." }], just: true },
  { type: "h0", num: "5.", runs: [{ t: "SUBMISSION GUIDELINES", b: true }] },
  { type: "n1", num: "5.1", runs: [{ t: "All Entries must conform to the guidelines below (“" }, { t: "Submission Guidelines", b: true }, { t: "”) and be in good taste and in keeping with Colin and Samir’s and Sponsor’s image, as determined in their sole discretion. By submitting an Entry in this Promotion each Participant warrants and represents that (i) he/she has the legal right and necessary permission(s) to do so (including permission from any associated Contributors), and (ii) his/her Entry (including all creative and other content comprising his/her Entry) conforms to the Submission Guidelines:" }], just: true },
  { type: "n2", num: "(A)", runs: [{ t: "Entries must meet Entry Requirements outlined in Section 4.1 and demonstrate the Judging Criteria attributes in Section 8.1;" }], just: true },
  { type: "n2", num: "(B)", runs: [{ t: "Entries must contain only original content (text, images, artwork, footage, audio, music, performance, and other original materials) created by the Participant and associated Contributors, if applicable, and, if required for entry, any idea, question, or similar statement submitted by Participant, must reflect a coherent and complete thought;" }], just: true },
  { type: "n2", num: "(C)", runs: [{ t: "Entries must not have been previously selected a winner in a prior promotion of any kind, or used for any other commercial, or non-personal public purpose;" }], just: true },
  { type: "n2", num: "(D)", runs: [{ t: "If the likeness of a person appears in an Entry, it should be only that of the Participant or any associated Contributors. However, if an Entry contains the likeness of persons other than the Participant and any associated Contributors, then by submitting the Entry, the Participant represents he/she has permission from all recognizable persons (including all Contributors, or the parent or legal guardian of any minor  child) featured in the Entry to use such person’s name and/or likeness, and to grant the rights granted to Colin and Samir and Sponsor in these Official Rules;" }], just: true },
  { type: "n2", num: "(E)", runs: [{ t: "Entries must not contain images or depictions of historical landmarks, or other content not created by the Participant and associated Contributors, if applicable, and must not infringe, violate, or use without permission the rights of any third party, including but not limited to trade names, trademarks, logos, privacy or publicity rights, or other intellectual property rights;" }], just: true },
  { type: "n2", num: "(F)", runs: [{ t: "Entries must be suitable for publication and viewing by all ages, and must not contain material that is indecent, obscene, tortious, defamatory, harassing, harmful, slanderous, libelous, disparaging, objectionable, or that promotes bigotry, racism, hatred, harm, or discrimination against any group, individual, or entity (as determined by Colin and Samir or Sponsor), or any other material that is unlawful, or in violation of or contrary to the laws or regulations in the jurisdiction from where the Entry is sourced or submitted; and" }], just: true },
  { type: "n2", num: "(G)", runs: [{ t: "Entries must not violate any online terms of use for the Site where the Entry- submitting mechanism for the Promotion may be hosted or the privacy policy applicable to the Promotion." }], just: true },
  { type: "n2", num: "(H)", runs: [{ t: "Each Entry must be created or edited using at least one Adobe product or service. Upon request, Participant must provide reasonable information or materials sufficient to verify such use. Failure to provide reasonable verification may result in disqualification." }], just: true },
  { type: "h0", num: "6.", runs: [{ t: "DATA PROTECTION", b: true }] },
  { type: "n1", num: "6.1", runs: [{ t: "Participants’ Consent to use of Personal Data. By participating in this Promotion and submitting an Entry each Participant consents to having personal data collected from him/her by Colin and Samir and Sponsor, which personal data may be transferred, and will be used and disclosed by Colin and Samir, Sponsor and their authorized agents for purposes of Promotion administration and prize fulfillment. By entering, each Participant consents to the collection, use and disclosure of his/her personal data as described in these Official Rules. Nothing in these Official Rules will be deemed to restrict or exclude any Participant’s statutory consumer rights pertaining to personal data. Except as otherwise stated in these Official Rules or on the Site, by participating in this Promotion and submitting an Entry each Participant consents to all of the terms and conditions of the Sponsor’s Privacy Policy, which is available at ", b: true }, { t: "https://www.adobe.com/privacy/policy.html ", b: true, i: true }, { t: "Participants’ License and Consent to use of Entries.", b: true }] },
  { type: "n2", num: "(A)", runs: [{ t: "By participating in the Promotion and submitting an Entry, each Participant grants to Colin and Samir, and its agents, affiliates, successors, licensees, assigns, production partners, advertising and promotional agencies, authorized designees, a worldwide, perpetual, irrevocable, royalty-free, nonexclusive, transferable right and fully-paid up, fully-sublicensable license, under any and all rights in and to the Entry, to use, modify, reproduce, edit, excerpt, adapt, translate, reformat, distribute, transmit, publicly perform, publicly display, publish (or not publish), and otherwise exploit the Entry, in whole or in part, together with or without Participant’s name, voice, image, likeness, biographical information, social-media handle and hometown (collectively, “Persona”), in any media or format now known or later developed. Without limiting the foregoing, an Entry may be used in connection with the administration, judging, advertising, marketing and promotion of the Contest, and related content, including in podcasts, podcast video and audio episodes, clips, trailers, compilations, behind-the-scenes content, reaction or commentary content, YouTube videos, social-media posts, newsletters, websites, and paid and organic advertising and promotional materials. The foregoing rights apply whether or not the Entry is selected as a Finalist or winning Entry and may be exercised without further notice, approval, attribution or compensation, except for the Prize expressly described in these Official Rules. Colin and Samir may remove, discontinue or decline to use any Entry at any time if such Entry does not comply with these Official Rules." }], just: true },
  { type: "n2", num: "(B)", runs: [{ t: "To the extent permitted by law, by submitting an Entry each Participant unconditionally and irrevocably waives any and all moral rights to which Participant may be entitled under applicable law, and waives and releases the Released Parties from any and all claims that he/she (and anyone by or through him/her) may have now or in the future in any jurisdiction based on “moral rights” with respect to the exploitation of his/her Entry by the Released Parties without further notification or compensation to the Participant. \"Moral Rights\" means any right to (a) divulge the Entry to the public; (b) retract the Entry from the public; (c) object to any modification of the Entry; or (d) any and all rights similar to moral rights existing under judicial or statutory law of any country or jurisdiction in the world, or under any treaty regardless of whether such right is generally called or referred to as a moral right. If this waiver of moral rights is unenforceable or invalid, and to avoid any doubt, each Participant acknowledges and agrees that  the Released Parties are authorized to exercise all moral rights to his/her Entry." }], just: true },
  { type: "n2", num: "(C)", runs: [{ t: "Participation in the Promotion creates no obligation (express or implied) on the part of Colin and Samir and/or Sponsor’s to use, commercialize or otherwise exploit any Participant’s Entry or Persona and no Participant is entitled to any damages or other relief by reason of Colin and Samir’s and/or Sponsor’s use or non-use of his/her Entry. Each Participant waives any right he or she may have to be mentioned as the author or creator of the Entry." }], just: true },
  { type: "n1", num: "6.2", runs: [{ t: "Participants’ Right to Opt-Out from the use of their Personal Data. ", b: true }, { t: "Each Participant may refuse to have his/her personal information collected, transferred, used, or disclosed as described in these Official Rules (“Opt- Out”) by choosing to not participate in the Promotion." }], just: true },
  { type: "n1", num: "6.3", runs: [{ t: "No Opt-In to future communications required to participate. ", b: true }, { t: "During the Promotion Period Participants may be presented the option to “Stay informed via email about Colin and Samir and/or Sponsor’s products and services.” (“Opt- In“ consent to future marketing), but Opt-In consent to future marketing is not required to participate in the Promotion, and will not increase or improve a Participant’s opportunity to win a prize." }], just: true },
  { type: "h0", num: "7.", runs: [{ t: "PARTICIPANTS’ ACKNOWLEDGEMENT", b: true }] },
  { type: "n1", num: "7.1", runs: [{ t: "By participating in this Promotion, each Participant understands and acknowledges that Colin and Samir and/or Sponsor may have developed, commissioned or acquired, or may currently or in the future be developing, commissioning or acquiring, apps, products, services, designs or materials similar or identical to the Participant’s Entry and each Participant waives any claims resulting from or in connection with any similarities to their Entry." }], just: true },
  { type: "h0", num: "8.", runs: [{ t: "JUDGING PHASE; PROCEDURE FOR BREAKING TIES", b: true }] },
  { type: "n1", num: "8.1", runs: [{ t: "Judging Phase: ", b: true }, { t: "During the Judging Phase, a panel of qualified judges designated by Colin and Samir and Sponsor (“" }, { t: "Judges", b: true }, { t: "”) will, in their sole discretion, evaluate and score all eligible Entries received and select the Participants with the highest-ranked Entries  (“" }, { t: "Finalist(s)", b: true }, { t: "”) based on each Entry’s cumulative score using the below weighted criteria (“" }, { t: "Judging Criteria", b: true }, { t: "”):" }], just: true },
  { type: "n2", num: "(A)", runs: [{ t: "25% " }, { t: "Concept: Is the entry clear, original and unique to the creator?", i: true }], just: true },
  { type: "n2", num: "(B)", runs: [{ t: "25% " }, { t: "Expression: Is idea expressed clearly and convincingly? Does the entry hit the brief requirements?", i: true }], just: true },
  { type: "n2", num: "(C)", runs: [{ t: "25% " }, { t: "Technique and skill in creating the entry", i: true }], just: true },
  { type: "n2", num: "(D)", runs: [{ t: "25% Practical Logistics: " }, { t: "Can this concept be executed?", i: true }], just: true },
  { type: "n1", num: "8.2", runs: [{ t: "Procedures for breaking ties.", b: true }] },
  { type: "n2", num: "(A)", runs: [{ t: "In the unlikely event of a tie in scoring after conclusion of the Judging Phase, a Finalist among the tying Entries will be selected based on the Entry with the highest score in the “Originality and creativity of the idea” category. Judges reserve the right in their sole discretion to select fewer than the stated number of Finalists if there is an insufficient number of eligible Entries, or an insufficient number of eligible Entries meeting the minimum Judging Criteria." }], just: true },
  { type: "h0", num: "9.", runs: [{ t: "WINNER SELECTION AND NOTIFICATION; ODDS OF WINNING", b: true }] },
  { type: "n1", num: "9.1", runs: [{ t: "Winner Selection and Notification. ", b: true }, { t: "Potential winner(s) will be determined on or about September 22, 2026 and notified by the email or direct message specified at the time of entry." }], just: true },
  { type: "n2", num: "(A)", runs: [{ t: "Potential winners may be required to complete and return a Declaration of Eligibility and, except where prohibited, Liability/Publicity Release, or other documents in the form within 3 days of Colin and Samir’s time stamp of sending in order to claim the prize. If a potential winner is 18 years of age as required, but deemed a minor in his or her jurisdiction, then the prize will be awarded in the name of the minor’s parent or legal guardian, who will be responsible for signing any necessary documents." }], just: true },
  { type: "n2", num: "(B)", runs: [{ t: "If a potential winner cannot be contacted, is contacted and does not respond within 3 days with all required information, fails to claim the prize as directed within the time allotted following attempted notification, refuses the prize, is ineligible to accept the prize, is otherwise not in compliance with these Official Rules, or if the attempted prize notification is returned as undeliverable, then the prize at issue will be forfeited and, at Colin and Samir’s and Sponsor’s discretion, not awarded or awarded to an alternate winner with the next highest-ranking Entry based on Community judging." }], just: true },
  { type: "n2", num: "(C)", runs: [{ t: "A Participant is not a winner, even if a prize notification is received, unless and until the Participant’s eligibility and the potential winning Entry has been verified and the Participant notified that verification is complete. Potential winners must continue to comply with these Official Rules." }], just: true },
  { type: "n1", num: "9.2", runs: [{ t: "Odds of winning. ", b: true }, { t: "This is a skill-based Contest and chance plays no part in determining the winner(s). The odds of winning a prize will depend on the number and quality of eligible Entries received, and the relative skill of each Participant." }], just: true },
  { type: "h0", num: "10.", runs: [{ t: "TOTAL PRIZES TO BE AWARDED; PRIZE DESCRIPTION; RETAIL VALUE (RV); DISTRIBUTION OF PRIZES FOR TEAM ENTRIES", b: true }] },
  { type: "n1", num: "10.1", runs: [{ t: "Total prizes to be awarded, descriptions, and aggregate RV. ", b: true }, { t: "One (1) Grand Prize will be awarded in this Promotion. The Grand Prize will consist of: (i) a cash grant award of $25,000 USD to be provided by Sponsor through its authorized pay agent Golin/Harris International, Inc. and used by the winner toward developing, producing or completing the creative project described in the winning Entry, (ii) the opportunity for the winner to travel to Los Angeles, California and participate in the recording of an episode of Colin and Samir’s Creator Support podcast or video program relating to the winning Entry and project, as arranged by Colin and Samir (subject to the execution of an appearance release and agreement); and (iii) round-trip coach airfare and reasonable hotel accommodations for the winner in connection with that appearance, as arranged by Colin and Samir.. The approximate retail value of the travel component will depend on the winner’s location and travel arrangements. The opportunity to participate in Creator Support has no separately stated retail value." }], just: true },
  { type: "body", runs: [{ t: "As a material condition of accepting the Grand Prize, the winner must use one or more Adobe products or services for the creative, production, or post-production process for the Entry (e.g., editing, design, visual effects, audio, or motion graphics), and cannot use competitive product/service alternatives. The foregoing does not include incidental use such as file storage, viewing, or communication." }] },
  { type: "body", runs: [{ t: "The winner agrees to reasonably cooperate with Colin and Samir in documenting and discussing such use in connection with the winner’s appearance on Creator Support and related promotional content. The winner remains responsible for developing and producing the project. Colin and Samir and Sponsor  is not obligated to supervise, finance beyond the stated cash award, complete, distribute, market or otherwise exploit the winner’s project." }] },
  { type: "n2", num: "(A)", runs: [{ t: "Retail Values (RVs) quoted represent the maximum retail price or, in the absence of a maximum retail price, the prevailing market price to the best of the Colin and Samir’s knowledge. Differences in stated price and actual prize values (including differences in any stated price and the price a winner would have had to pay for such product in any jurisdiction) will not be awarded. Prizes are non-transferable and all prize details, including type, color, size, etc. are at Colin and Samir’s and Sponsor’s sole discretion. ALL PRIZES ARE AWARDED “AS IS” WITH NO WARRANTY OR GUARANTEE, EITHER EXPRESS OR IMPLIED. " }, { t: "Participants are responsible for all applicable federal, state, territorial, provincial, municipal and local taxes, costs associated with currency exchange, or any other costs and expenses associated with prize receipt, acceptance, or use. ", b: true }, { t: "Use of any prize(s) that have associated use terms such as gift cards, software, online services, or subscription products is subject to any terms or conditions that may accompany such products as issued by the service or product provider. Only the advertised number of prizes and those claimed in accordance with these Official Rules will be awarded. Winners may be required to provide a shipping address and proof of residency to claim a prize. Colin and Samir and Sponsor will arrange and determine mode of delivery of prizes to winners. Allow 2 weeks for delivery of a prize." }], just: true },
  { type: "n2", num: "(B)", runs: [{ t: "Distribution of prizes involving team Submissions. ", b: true }, { t: "Prizes will be delivered only to the winner who submitted the Entry containing the Submission and division of the prize (among Contributors who participated in development of the Submission) is solely the winner’s responsibility." }], just: true },
  { type: "n2", num: "(C)", runs: [{ t: "Terms in this Section 10.1(C) additionally apply to the travel and Creator Support appearance component of the Grand Prize (“Trip”). The Trip includes round-trip economy/coach class airfare (or other travel arrangement depending on winner’s proximity to Los Angeles) for the winner from the commercial airport nearest the winner’s residence to Los Angeles, California; round-trip airport transportation selected by Colin and Samir; and accommodations at a hotel selected by Colin and Samir (one standard room). The winner must be willing and able to travel to Los Angeles and participate in the recording of Creator Support on a mutually agreed date during September 2026. Colin and Samir will consult with the winner in good faith regarding scheduling, but all production dates, locations and arrangements remain subject to Colin and Samir’s reasonable production requirements. If the parties cannot agree on a September 2026 recording date after reasonable good-faith efforts, Colin and Samir may propose an alternative date or remote participation arrangement. If the winner refuses or is unable to participate on a reasonably proposed date or fails to comply with reasonable production requirements, the Prize may be forfeited, and an alternate winner may be selected. The winner is solely responsible for all costs and expenses not expressly provided as part of the Trip, including meals, gratuities, baggage fees, incidentals, ground transportation not arranged by Colin and Samir, and any additional or extended travel. Travel and accommodations must be booked through Colin and Samir or its designated agent and are subject to availability, carrier and hotel terms, and applicable restrictions. The winner must possess all identification and other documentation required for travel and is responsible for complying with all applicable travel requirements. If the travel or appearance component is cancelled, postponed or rendered impracticable due to circumstances beyond Colin and Samir’s reasonable control, Colin and Samir may substitute a remote appearance, an alternative date or a prize component of equal or greater value, or may award the remaining components of the Prize in full satisfaction of the Prize obligation." }], just: true },
  { type: "n2", num: "(D)", runs: [{ t: "By accepting the Prize, the winner agrees to participate in photography, filming, audio recording, interviews and other production activities relating to the Contest, the winning Entry, the project and Creator Support. The winner irrevocably grants to Colin and Samir, Sponsor, and their successors, licensees, assigns and authorized designees the right to photograph, record, reproduce, edit, modify, dub, synchronize, distribute, publicly perform, publicly display, advertise, promote and otherwise exploit the winner’s name, image, likeness, voice, biographical information, statements, performance, appearance and all resulting footage, recordings and materials, in connection with the foregoing, in whole or in part, in any media now known or later developed, throughout the universe, in perpetuity, without further notice, approval or compensation. As between the winner and Colin and Samir, Colin and Samir will exclusively own all footage, recordings and other results and proceeds created in connection with the winner’s appearance in any Creator Support episode(s), including all copyrights therein. Colin and Samir has no obligation to produce, release, distribute or otherwise use any episode or materials featuring the winner. The winner may be required to execute Colin and Samir’s customary appearance release and other reasonable production documents as a condition of travel, participation and receipt of the Prize." }], just: true },
  { type: "h0", num: "11.", runs: [{ t: "PARTICIPANTS’ AGREEMENT TO OFFICIAL RULES AND DECISIONS OF COLIN AND SAMIR AND JUDGES. ", b: true }, { t: "Participation in the Promotion or receipt of any prize constitutes each Participant’s and winner’s full and unconditional agreement to and acceptance of these Official Rules, the Site terms, and the " }, { t: "Privacy Policy (", u: true }, { t: "at https://www.adobe.com/privacy/policy.html) incorporated into these Official Rules by this reference), and Colin and Samir’s, Sponsor’s and Judges’ decisions which are final and binding in all matters related to the Promotion. Winning a prize is contingent upon Participant fulfilling all applicable requirements in these Official Rules." }], just: true },
  { type: "h0", num: "12.", runs: [{ t: "GENERAL", b: true }] },
  { type: "n1", num: "12.1", runs: [{ t: "Colin and Samir’s right to cancel, terminate or modify the Promotion. ", b: true }, { t: "Colin and Samir reserves the right to cancel, terminate, or modify the Promotion, or any portion thereof, if in Colin and Samir’s opinion the Promotion has been compromised, corrupted, or cannot be completed as planned due to computer virus, bugs, tampering, unauthorized intervention, technical failures, or other conditions beyond Colin and Samir’s reasonable control, including without limitation, an insufficient volume of participation or eligible Entries, and to select potential winner(s) from among eligible, non-suspect Entries received on or before the termination date. While Colin and Samir may take action against fraudulent activities of Participants, Colin and Samir assumes no responsibility or obligation to proactively police Participants’ activities, or to investigate any or all claims of fraudulent activity. Colin and Samir’s failure to enforce any provision of these Official Rules does not constitute a waiver of that provision." }], just: true },
  { type: "n1", num: "12.2", runs: [{ t: "Limitations of liability. ", b: true }, { t: "The Released Parties (defined in Section 2.3) do not guarantee the processing or posting of any Entry or Vote, or the functioning of the Site. The Released Parties are not in any way responsible or liable for any act, omission, or breach of contract or warranty by Participants, or any infringement or violation of any right of publicity, privacy, intellectual property or proprietary rights, or for any loss (including loss of opportunity) or other claim arising from or in relation to the Promotion, or any Entry or Vote submitted, or for the authorized or unauthorized actions of Participants or other third parties. The Released Parties are not responsible for events requiring a cancellation or postponement of the Promotion, or for Entries or Votes that are incomplete, illegible, lost, intercepted, misdirected, or not otherwise received by Colin and Samir, or for hardware or software malfunctions, delayed, unavailable, or failed network connections or communications, or other errors or impediments of any kind, whether technical or non-technical in nature, relating to the Promotion, its administration, the processing of Entries or Votes, or the announcement of winners." }], just: true },
  { type: "n1", num: "12.3", runs: [{ t: "Release of claims. ", b: true }, { t: "By participating in the Promotion each Participant agrees, to the maximum extent allowable under applicable law, to release and hold the Released Parties harmless from and against any and all liability whatsoever for any injuries, losses, or damages of any kind arising from, or in any way connected with, participation in the Promotion, any Promotion-related activity, or any Entry submitted, or the shipping and handling, receipt, possession, loss, use or misuse of any prize awarded. The limitation of liability in this section does not apply to claims for personal injury or death caused by Colin and Samir or its agents’ negligence, or to liability of Colin and Samir and its agents for willful misconduct or gross negligence, or any other liabilities that may not be excluded by law. Participants agree that Colin and Samir’s and Sponsor’s only obligation is to accept eligible Entries and submit them to the Promotion Judges (and ultimately to award prizes) according to the procedures and criteria set forth in these Official Rules, that these obligations are fair and adequate consideration for any Entry submitted, and Participant is not entitled to and will not seek any further compensation." }], just: true },
  { type: "n1", num: "12.4", runs: [{ t: "Not an offer or contract of employment. ", b: true }, { t: "This is a Promotion for prizes only and " }, { t: "NOT AN OFFER OR CONTRACT FOR EMPLOYMENT", u: true }, { t: ". Under no circumstances will participation in this Promotion, the submission of an Entry, awarding of a prize, or anything in these Official Rules be construed as an offer or contract of employment with Colin and Samir. Each Participant acknowledges and agrees that no confidential, fiduciary, agency, or other special relationship or implied-in-fact contract now exists between him/her, Colin and Samir and or Sponsor, and no such relationship is established by Participant’s decision to submit an Entry in this Promotion." }], just: true },
  { type: "n1", num: "12.5", runs: [{ t: "Governing law; venue; disputes", b: true }, { t: ". All issues and questions concerning the construction, validity, interpretation, and enforceability of these Official Rules, or the rights and obligations of the parties hereunder, will be governed by, and construed in accordance with, the laws of the state of California, United States of America, without giving effect to any choice of law or conflict of law rules or provisions (whether of the State of California or any other jurisdiction) that would cause the application of laws of any jurisdiction other than the State of California, and all claims must be resolved in the appropriate State Court located in Santa Clara County, California." }], just: true },
  { type: "n1", num: "12.6", runs: [{ t: "Winners list. ", b: true }, { t: "After all winners have been determined and verified, and no later than 45 days after on or about September 17, 2026, a winners list may be available on request" }], just: true },
];
